name: artificialintelligence
favicon: null
layout_spectrum: 0.40583
typography_spectrum: 0.29665179806761444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e8cb'
    - '#2c4947'
    - '#709f8f'
    - '#b8aa8f'
    - '#b68b58'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
