name: artificialintelligence
favicon: null
layout_spectrum: 0.10248
typography_spectrum: 0.29665179806761444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e8cb'
    - '#2c4947'
    - '#709f8f'
    - '#b8aa8f'
    - '#b68b58'
  brandStrength: 1
  lightness: 0.02060110680758953
  saturation: 0.6170333928894252
  rhythmicContrast: 0.8700149185024202
purpose: []
