typography_spectrum: 0.85915
content_rating:
  adult: false
color:
  brandColors:
    - '#e5e8cb'
    - '#2c4947'
    - '#709f8f'
    - '#b8aa8f'
    - '#b68b58'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.31345
analytics:
  google: null
  facebook: null
  twitter: null
name: artificialintelligence
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/5ab6ec29-70d0-4c6e-a485-dc12c65018a3.jpg'
title: A.I. Is Taking Over The World
purpose: []
