name: artificialintelligence
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/5f1ff323-c59e-41f6-8c83-0bbdd382eb0e.jpg'
layout_spectrum: 0.38824
typography_spectrum: 1
content_rating:
  adult: false
title: A.I. Is Taking Over The World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e8cb'
    - '#2c4947'
    - '#709f8f'
    - '#b8aa8f'
    - '#b68b58'
  brandStrength: 0
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 1
purpose: []
