name: artificial intelligence
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5f1ff323-c59e-41f6-8c83-0bbdd382eb0e.jpg
layout_spectrum: 0.05343850841745734
typography_spectrum: 0.5963459978811443
title: A.I. Is Taking Over The World
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content_rating:
  adult: false
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.09691994800232351
  lightness: 0.42557237786240876
  saturation: 0.010985191212967038
  rhythmicContrast: 0.925470958231017
purpose: []
