name: artificial intelligence
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5f1ff323-c59e-41f6-8c83-0bbdd382eb0e.jpg
layout_spectrum: 0.6341764458920807
typography_spectrum: 1
title: A.I. Is Taking Over The World
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content_rating:
  adult: false
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0
  lightness: 0.8612983145285398
  saturation: 0.2478726755362004
  rhythmicContrast: 0.22072598803788424
purpose: []
