name: artificialintelligence
favicon: null
layout_spectrum: 0.8559848754666746
typography_spectrum: 0.29665179806761444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7650106472428888
  lightness: 0.02060110680758953
  saturation: 0.6170333928894252
  rhythmicContrast: 0.8700149185024202
purpose: []
